/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as EventEventIdEditRouteImport } from './routes/event.$eventId_.edit'
import { Route as ApiPublicHooksSendEventRemindersRouteImport } from './routes/api/public/hooks/send-event-reminders'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdEditRoute = EventEventIdEditRouteImport.update({
  id: '/event/$eventId_/edit',
  path: '/event/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendEventRemindersRoute =
  ApiPublicHooksSendEventRemindersRouteImport.update({
    id: '/api/public/hooks/send-event-reminders',
    path: '/api/public/hooks/send-event-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/event/$eventId/edit': typeof EventEventIdEditRoute
  '/api/public/hooks/send-event-reminders': typeof ApiPublicHooksSendEventRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/event/$eventId/edit': typeof EventEventIdEditRoute
  '/api/public/hooks/send-event-reminders': typeof ApiPublicHooksSendEventRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/event/$eventId_/edit': typeof EventEventIdEditRoute
  '/api/public/hooks/send-event-reminders': typeof ApiPublicHooksSendEventRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/login'
    | '/saved'
    | '/event/$eventId'
    | '/settings/notifications'
    | '/settings/profile'
    | '/event/$eventId/edit'
    | '/api/public/hooks/send-event-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/login'
    | '/saved'
    | '/event/$eventId'
    | '/settings/notifications'
    | '/settings/profile'
    | '/event/$eventId/edit'
    | '/api/public/hooks/send-event-reminders'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/login'
    | '/saved'
    | '/event/$eventId'
    | '/settings/notifications'
    | '/settings/profile'
    | '/event/$eventId_/edit'
    | '/api/public/hooks/send-event-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  LoginRoute: typeof LoginRoute
  SavedRoute: typeof SavedRoute
  EventEventIdRoute: typeof EventEventIdRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  EventEventIdEditRoute: typeof EventEventIdEditRoute
  ApiPublicHooksSendEventRemindersRoute: typeof ApiPublicHooksSendEventRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId_/edit': {
      id: '/event/$eventId_/edit'
      path: '/event/$eventId/edit'
      fullPath: '/event/$eventId/edit'
      preLoaderRoute: typeof EventEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-event-reminders': {
      id: '/api/public/hooks/send-event-reminders'
      path: '/api/public/hooks/send-event-reminders'
      fullPath: '/api/public/hooks/send-event-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendEventRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  LoginRoute: LoginRoute,
  SavedRoute: SavedRoute,
  EventEventIdRoute: EventEventIdRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  EventEventIdEditRoute: EventEventIdEditRoute,
  ApiPublicHooksSendEventRemindersRoute: ApiPublicHooksSendEventRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
